# -*- coding: utf-8 -*-
"""pandas_day_7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_m4riw02H-J2ujjfAf3ZNuOTmzQ_31UW
"""

# polymer ai using create a report

import numpy as np
import pandas as pd

df = pd.read_csv("/content/Attrition - Attrition.csv")
df.head()

!pip install plotly

import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default = "plotly_white"

print(df.isnull().sum())

#check percantage of attrition by department
# filter the data to show only "yes" values in the "attrition" column

attr_df = df[df['Attrition']=='Yes']
attr_df

attr_df

# calculate the attrition by department

attrition_by_dpt = attr_df.groupby(['Department']).size().reset_index(name = "count")

attrition_by_dpt

# create a donut chart
fig = go.Figure(data=[go.Pie(
    labels = attrition_by_dpt['Department'],
    values = attrition_by_dpt['count'],
    hole=0.4,
    marker=dict(colors=['red','green']),
    textposition='inside'
)])

#update the layout
fig.update_layout(title='Attrition by Department')

# show the chart
fig.show()

edu_df = df[df['Attrition']=='Yes']
edu_df

education_field = edu_df.groupby(['EducationField']).size().reset_index(name = "count")

education_field

# create a donut chart
fig = go.Figure(data=[go.Pie(
    labels = education_field['EducationField'],
    values = education_field['count'],
    hole=0.4,
    marker=dict(colors=['red','green']),
    textposition='inside'
)])

fig.show()

# we can see that the employees with life sciences as an education field have a high attrition rate. now let's have
# a look at the percantage of attrition by number of years at the company.

attrition_by = attr_df.groupby(['YearsAtCompany']).size().reset_index(name='count')
attrition_by

# we can see that most of the employees leave the organization after completing a year.
#

attrition_by = attr_df.groupby(['YearsSinceLastPromotion']).size().reset_index(name='count')
attrition_by

# we can see that the employees who dont get promotions leave the organization more compared to the employees who got
# promotions. now lets have a look at the percatage of attrition by gender.

attrition_by = attr_df.groupby(['Gender']).size().reset_index(name='count')
attrition_by
# create a donut chart
fig = go.Figure(data=[go.Pie(
    labels = attrition_by['Gender'],
    values = attrition_by['count'],
    hole=0.4,
    marker=dict(colors=['yellow','green']),
    textposition='inside'
)])
#update the layout
fig.update_layout(title='Attrition by Gender')
# show the chart
fig.show()

# men have a high attrition rate compared to women. now lets have a look at the attrition by analyzing the relationship btw
# monthly income and the age of the employees.
import plotly.express as px

fig = px.scatter(df, x="Age" , y="MonthlyIncome", color="Attrition", trendline="ols")
fig.update_layout(title="Age vs. monthly income by Attrition")
fig.show()

# using data analytics