# -*- coding: utf-8 -*-
"""pandas_day_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13O8i3hNgOVEMdvqLUqud3Ak5Dpm1ipad
"""

# parts of EDA
# 1.  univariate analysis :- analysis on a single independent column
# 2.  bivariate analysis :- analysis on two independent columns
# 3.  multivariate analysis :- analysis on multiple independent columns

# data types
# 1. numerical data :- continuous data (age,height , weight,etc)
# 2. categorical data :- discrete data (total number of employees , marital status , student result)

import numpy as np
import pandas as pd

# !pip install matpotlib
# !pip install seaborn

df = pd.read_csv("/content/titanic - titanic.csv")

import matplotlib.pyplot as plt #visualization library
import seaborn as sns # matplotlib's updated version is seaborn

df = pd.read_csv("/content/titanic - titanic.csv")

df.head()

"""# univariate analysis"""

df.columns

df['Survived'].value_counts()

sns.countplot(x = df['Survived'])

# if we want to see actual values then we use value_counts().
df['Survived'].value_counts()

df['Survived'].value_counts().plot(kind = 'bar')

# if we want to find out percantage then use piechart.
df['Survived'].value_counts()

df['Survived'].value_counts().plot(kind = 'pie' , autopct = '%.2f')

# if we have numerical data then we use histogram because it finds the distribution

plt.hist(x=df['Age'])
plt.show()

#  if we have numerical data then we use histogram

# from typing import dataclass_transform
# 2. boxplot
# for find our outliers
# 1. lower fence
# 2. 25% data
# 3. IQR (interquartile range)
# 4. 75% data
# 5. upper fence

# x = 1,2,3,4,5
# mean = 15/5 = 3 here 100 is outlier
# x = 1,2,3,4,5,,100
# mean = 115 / 6 = 19.3

sns.boxplot(x = df['Age'])

tips = sns.load_dataset("tips")
tips

"""bivarite analysis"""

#1. scatterplot ( numerical column - numerical column)

sns.scatterplot(x = tips['total_bill'],
                y = tips['tip']) # df['total_bill']

# hue , colur , style helps in representing relation btw 2 or more columns on the basis of any third condtition.
sns.scatterplot(x="total_bill", y="tip", data=tips, hue = tips['sex'])



