# -*- coding: utf-8 -*-
"""pandas_day_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_-ekCbwsLL957IlBA2AFw3B35Vc0ohy
"""

import pandas as pd

df = pd.read_csv('/content/covid_toy - covid_toy (1).csv')
df

### top data check, we will use df.head() , by default it returns top 5 rows.
df.head(2)

### bottom data check , we will use df.tail() , by defaults it returns last 5 rows.
df.tail(3)

### if you want random indexed data, then we will use df.sample(). by default it will return
# single row.
df.sample()

### if we want to check data type of each column. df.dtypes
df.dtypes

### if we want to check overall information then we will use df.info()
df.info()

# if you want to check statical view of data , then you can use df.describe()
df.describe()

df.head(2)

### if you want to check  missing data in df, then will use df.isnull().sum()

df.isnull().sum() ## here fever has 10 missing values.

#x = 1,2,3,nan,5
# mean = (1+2+3+5)/4 = 11/4 = 2.75
# we will fill this value in this missing data.
x = 1,2,3,2.75,5

df['fever'] = df['fever'].fillna(df['fever'].mean())

df.isnull().sum()

df.head(1)

# if you have categorical data , and you want to check total sub-categories then
# we will use df['column_name'].value_counts()

df['gender'].value_counts()

#### machine -----> numbers ---->

df['gender'] = df['gender'].map({"Female":1,"Male":0})

df.head(5)

df['cough'].value_counts()

df['cough'] = df['cough'].map({"Mild":0,"Strong":1})

df.sample(5)

#has_covid,city

df['has_covid'] = df['has_covid'].map({"No":0,"Yes":1})

df.head()

df['city'] = df['city'].map({"Kolkata":0,"Delhi":1,"Mumbai":0.1})

df.head()