# -*- coding: utf-8 -*-
"""pandas_day_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkCFu5QS8Ss0LH5rqhRg7BaFbm8lJwVP
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/placement - placement.csv")

df

df.head(5) # top 5 data

df.tail(5)  # bottom 5 data

df.describe() # statically view of data

df.info()  # data frame information

top_left_corner_df = df.iloc[:4 , :3] # iloc[row_range , column_range]
top_left_corner_df

df.loc[1:3 , ['cgpa','placed']]  # loc[row_range , column_names]

s = df.axes
s

p = df.dtypes
p

df['cgpa'].dtypes

b = df.empty ### it returns true if there any missing data in dataframe otherwise returns false.
b

df.isnull().sum() ##  for checking missing values.

df = df.dropna() ## for remove missing row

i = df.ndim ## number of axes (it is 2)
i

t = df.shape ## shape = n(rows) , n (columns)
t
df.shape[0]   ###### total rows in data
df.shape[1]   ##### total columns in data

d = df.size  # row count * column count
d

a = df.values # get a numpy array for df
a

df = df.copy()

p = df.sort_values(by = 'resume_score')
p

### tips data set ---->
#categorical column -- numerical columns convert using map()
# rows,columns, loc,iloc,1column sort

import pandas as pd
import numpy as np

df = pd.read_csv("/content/tips - tips.csv")

df.head()

df.tail()

df['sex'] = df['sex'].map({'Female': 0, 'Male': 1})
df['smoker'] = df['smoker'].map({'No': 0, 'Yes': 1})

df.head()

tip_data = df.iloc[:4 , :3]
tip_data

df.loc[1:3 , ['sex','tip','time']]

tip_data.sort_values('total_bill')

t = df.shape
t

df.shape[0]
df.shape[1]