# -*- coding: utf-8 -*-
"""pandas_day_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTMGa9kIHEDTaww3niYr5IPOPWRaJGGk
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/placement - placement (1).csv")

df

# x = df.astype(int)  # type conversion
df['cgpa'] = df['cgpa'].astype(int)
df

df['cgpa'] = df['cgpa'].add(10)

df

r = df['cgpa'].mean()
r

s = df['cgpa'].median()
s

g = df.filter(items = ['cgpa','placed'])
g
df[['cgpa' , 'placed']]  ### second option of filtering

s = df.filter(items = [5,6], axis = 0)   ### axis = 0 means row wise operation

s

q = df.to_string()  # save in string
q

e = df.to_csv("path_location")

idx = df.columns
idx

label = df.columns[0] # first column label
label

p = df.columns.tolist()
p  #

q = df.columns.values # array of column labels
q

p = df.rename(columns = {'cgpa':'updated_cgpa','resume_score':'semester_marks'})  # how to rename a culumn
p

df['half'] = df['cgpa'].where(df['cgpa']>17 , other = 0)
df.head(10)

# row = 11 to 13
# column= 3
# 2 clumn name rename
# column name ---> male customers
# total_bill  ---> integer

df = pd.read_csv("/content/tips - tips.csv")

df



df = df.rename(columns={df.columns[2]: 'male customers'})
df

df['total_bill'] = df['total_bill'].astype(int)
df

df = df.iloc[11:14]
df

# data ----> 1-1 column data type , top 6 data , data export csv , excel

df.dtypes

df.head(6)

df.to_csv("output.csv", index=False)

df.to_excel("output.xlsx", index=False)

# data
1. numerical :- coontinous data -- > we can divide further
# salary --> 20500.60 , weight --> 70.54 , distance (jaipur to delhi)=270.78km ,height, age
2. categorical :- discrete data -- > we can not divide further
# gender (m.f) , marital status(m,u), number of employees in an office,
covid data --> has_covid(y,n)--> map --> (1,0)
customer cage --> bill pay --> 452.78ruupe



