# -*- coding: utf-8 -*-
"""pandas__journey_day1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Rod8ipv0vZ0utSLEP_YfLmvNkJqGdkI
"""

# pandas :- pandas is an poen source library which is used for handle data manipulations.

import pandas as pd

# data structure of pandas :-
# 1. series ----> it stores only values not column name it os one-dimensniol.
# 2. dataframe ---> it store values with column name. and it is multi - dimensinal.

a = pd.Series([1,45,78,90])
a

type(a)

# ## dataframe

a = {
    "Emp_Id":[1,2,3,4,5],
    "Name":['akanksha','abhishek','vikas','gazal','riya'],
    "Department":['IT','Sales','IT','IT','Sales'],
    "Salary":[50000,34000,36000,37000,38000]
}

type(a)

df = pd.DataFrame(a)

df

### export this data into CSV

df.to_csv("Emp_data.csv")

## export this data into excel

df.to_excel("New_Emp_data.xlsx")

# import the data

a = pd.read_csv('Emp_data.csv')
a

d = pd.read_csv("/content/flipkart (1).csv")
d

# student_id , student_name, course_name,course_duration,total_fees isme 10 rows tk ka data
#  dataframe mai convert krna hai or uske baad us data
# ko csv and  excel mai export krna hai than these two data sets you have to create a new repo (data_students) and upload 2 datasets
# into github repo