# -*- coding: utf-8 -*-
"""practice on pandas data_analysis_28april

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LahiKWcMSURSmr1tsZaTmKXdeWn4VfL0
"""

#1. load the dataset and display first 10 rows and find the total number of rows & columns. & find list of all column name
#2. count unique values in department
#3. find number of employees who left means attrition = yes.
#4. filter employees whose age is greaton than 40
#5. select ony these columns age, department, monthly income.
#6. find employees with overtime is equal to yes
#7.add a new column the column name is income after hike
# = monthly income  + (monthly income * percent sallary hike % 100)
#8. rename column monthly income to sallary
#9. find average monthly income per department.
#10. find average age per job role
#11. find minimum distance from hone per dewpartment
#12.  find total employees per education field.
#13. find employees count grouped by marital status & attrition

import numpy as np
import pandas as pd

df = pd.read_csv("/content/Attrition - Attrition.csv")

# 1. load the dataset and display first 10 rows and find the total number of rows & columns. & find list of all column name
df.head(10)  # first 10 rows

# total rows & columns
df.shape

# find list of all column name
df.columns.to_list()

#2. count unique values in department
df['Department'].value_counts()

#3. find number of employees who left means attrition = yes.
# df[df['Attrition'] == 'Yes']
df[df['Attrition'] == 'Yes'].shape

#4. filter employees whose age is greaton than 40
df[df['Age'] > 40].shape

#5. select only these columns age, department, monthly income.
df[['Age', 'Department', 'MonthlyIncome']]

#6. find employees with overtime is equal to yes
df[df['OverTime'] == 'Yes'].shape

#7.add a new column the column name is income after hike (# = monthly income  + (monthly income * percent sallary hike % 100))
df['Income_After_Hike'] = df['MonthlyIncome'] + (df['MonthlyIncome'] * df['PercentSalaryHike'] / 100)

#8. rename column monthly income to sallary
df.rename(columns={'MonthlyIncome':'sallary'})

#9. find average monthly income per department.
df.groupby('Department')['MonthlyIncome'].mean()

#10. find average age per job role
df.groupby('JobRole')['Age'].mean()

#11. find minimum distance from home per department
df.groupby('Department')['DistanceFromHome'].min()

#12.  find total employees per education field.
df.groupby('EducationField')['EmployeeNumber'].count()

#13. find employees count grouped by marital status & attrition
df.groupby(['MaritalStatus', 'Attrition'])['EmployeeNumber'].count()