# -*- coding: utf-8 -*-
"""supply chain data_practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-12caHqTeAcExOdWFRnZInpKiMvrsdIj
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/supply_chain - supply_chain.csv")
df.head()

import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.templates.default ="plotly_white"

df.describe()

# now lets get started with analyzing the supply chain by looking at
# the relationshipbtw the price of the products and the revenue generated by them

# !pip install statsmodels

fig = px.scatter(df, x="Price",
                 y="Revenue generated",
                 color="Product type",
                 hover_data=["Number of products sold"],
                 trendline="ols")
# show chart
fig.show()

"""thus the comapny derives more revenue from skincare products, and the higghher the price of skincare produncts , the more revenue they generate. now lets have a look at the sales by product type

"""

Sales_data = df.groupby('Product type')['Number of products sold'].sum().reset_index()
#sales data
pie_chart = px.pie(Sales_data,
                   names='Product type',
                   title='Sales by Product Type',
                   hover_data=['Number of products sold'],
                   hole=0.5,
                   color_discrete_sequence=px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition='inside',textinfo='percent+label')
pie_chart.show()

"""total revenue by shipping carrier"""

total_revenue = df.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()

fig = go.Figure()
fig.add_trace(go.Bar(
    x=total_revenue['Shipping carriers'],
    y=total_revenue['Revenue generated']
))

fig.update_layout(
    title='Total Revenue by Shipping Carrier',
    xaxis_title='Shipping Carrier',
    yaxis_title='Revenue generated'
)

fig.show()

Sales_data = df.groupby('Product type')['Defect rates'].sum().reset_index()
#sales data
pie_chart = px.pie(Sales_data,
                   names='Product type',
                   values='Defect rates',
                   title='Defect Rate by Product Type',
                   hover_data=['Defect rates'],
                   hole=0.5,
                   color_discrete_sequence=px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition='inside',textinfo='percent+label')
pie_chart.show()

# product type m avg shipping time

Sales_data = df.groupby('Product type')['Shipping times'].mean().reset_index()

pie_chart = px.pie(Sales_data,
                   names='Product type',
                   values='Shipping times',
                   hover_data=['Shipping times'],
                   hole=0.5,
                   color_discrete_sequence=px.colors.qualitative.Pastel)

pie_chart.update_traces(textposition='inside', textinfo='percent+label')
pie_chart.show()

"""so the company is using three carriers for transporation, and carrier B helps the company in generating more revenue. now lets have a look at the avg lead time and avg manufacturing costs for all products of the company ."""



# implace :- original data m change krna
avg_lead_time = df.groupby('Product type')['Lead time'].mean().reset_index()
avg_lead_time

avg_manufactuting_costs = df.groupby('Product type')['Manufacturing costs'].mean().reset_index()
avg_manufactuting_costs

#

result = pd.merge(avg_lead_time, avg_manufactuting_costs, on='Product type')
result.rename(columns={'Lead time': 'Average lead time',
                       'Manufacturing costs': 'Average Manufacturing costs'}, inplace=True)
print(result)

"""**analyzing** ***SKU*** :-*** stock keeping unit***"""

revenue_chart = px.line(df, x='SKU',
                        y='Revenue generated',
                        title='Revenue generated by SKU')
revenue_chart.show()

"""there another column in the data set as stock levels. stock levels refer to the number of products a store or business has in its inventory . now lets have a look at the stock levels of sku."""

stock_chart = px.line(df, x='SKU',
                     y='Stock levels',
                     title='Stock levels by SKU')
stock_chart.show()

"""now lets have a look at the order quantity of each **SKU**"""

order_quantity_chart = px.bar(df, x='SKU',
                              y='Order quantities',
                              title='Order quantity by SKU')
order_quantity_chart.show()

"""cost analysis :- now lets analyze the shipping cost of carriers"""

shipping_cost_chart = px.bar(df, x='Shipping carriers',
                             y='Shipping costs',
                             title='Shipping costs by carrier')
shipping_cost_chart.show()
#

Sales_data = df.groupby('Transportation modes')['Costs'].mean().reset_index()
pie_chart = px.pie(Sales_data,
                   names='Transportation modes',
                   values='Costs',
                   title='cost distribution by transporation mode',
                   hover_data='Costs',
                   hole=0.5,
                   color_discrete_sequence=px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition='inside',textinfo='percent+label')
pie_chart.show()