# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4G-h33ACxp0ZgS-obDqFVIAIh0cxuwt
"""

import numpy as np
import pandas as pd

df.head()

# 1 what is d/f b/w series and data frame
# 2 d/f b/w loc and iloc
# 3 what is d/f b/w decribe and info
# 4 what is d/f b/w head  tail sample
# 5 how do u handle missing values using pandas
# 6 how do u filter data by the row and column
# 7 what is group by perform operation using group by
# 8 export your data into csv and exel format
# 9 how do u rename column

# 10 if you have two sub data frame in which a column is common now you have to merge these two dataframe into a single dataframe
#11  you have to update the values from 10 to 15 index number values of all columns.
#12 you have to convert categorical data to numerical data using map function.

# 1 what is d/f b/w series and data frame
# series :-  it stores only values not column name it os one-dimensniol.
a = pd.Series([1,2,3,4,5])
a

# dataframe :-  it store values with column name. and it is multi - dimensinal. it stores form of tabular.

df = pd.DataFrame({
    "Emp_Id":[1,2,3,4,5],
    "Name":['akanksha','abhishek','vikas','gazal','riya'],
    "Department":['IT','Sales','IT','IT','Sales'],
    "Salary":[50000,34000,36000,37000,38000]
})
df

# 8 export your data into csv and exel format
df.to_csv("Emp_data.csv")   # export this data into csv

df.to_excel("New_Emp_data.xlsx") # export this data into excel

df = pd.read_csv("/content/covid_toy - covid_toy (1).csv")
df

# 2 d/f b/w loc and iloc
# loc :- label (name) se select karta hai

df.loc[1:3,['city','fever']]  # Rows 1-3, specific columns by name

# iloc :-index number se select karta hai
df.iloc[:4, :3]  #first 4 rows ,first 3 columns

# 3 what is d/f b/w decribe and info
# describe :- its provide Statistical summary of numerical columns
df.describe()

# info :- it provide overal information in dataframe
df.info()

# 4 what is d/f b/w head  tail sample
# head :- Returns top n rows by default 5.
df.head()

# tail :-Returns last n rows by default 5.
df.tail()

# sample:- Returns n random rows by default 1.
df.sample()

# 5 how do u handle missing values using pandas
# check missing values
df.isnull().sum()   # shows count of missing values per column

# fillna() :- fills missing (NaN) values with a specified value — the mean, median, or mode of that column.
df['fever'] = df['fever'].fillna(df['fever'].mean())

# 6 how do u filter data by the row and column
# filter :- Select specific columns or rows from a DataFrame.
# Select specific columns by name
m = df.filter(items=['age', 'fever'])
m

fil = df[df['age'] > 25]  #condition bases filtering in rows
fil

df.loc[0:2, ["age"]]  #row + column filtering

# 7 what is group by perform operation using group by

# 9 how do u rename column
p = df.rename(columns={'age': 'Age','fever': 'Fever'})
# p

# 10 if you have two sub data frame in which
# a column is common now you have to merge these two dataframe into a single dataframe
df1 = df[['city', 'age']].head(10)
df2 = df[['city', 'fever']].head(10)


merged = pd.merge(df1, df2, on="city")
merged.head()

#11  you have to update the values from 10 to 15 index number values of all columns.
df.loc[10:15] = 0

#12 you have to convert categorical data to numerical data using map function.
df['city'] = df['city'].map({'Delhi': 1, 'Mumbai': 2, 'Kolkata': 3})
df['cough'] = df['cough'].map({'Mild': 1, 'Strong': 2, 'Normal': 3})
df['gender'] = df['gender'].map({'Male': 1, 'Female': 2})
df['has_covid'] = df['has_covid'].map({'Yes': 1, 'No': 2})

df.head()