# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Ez0qdNuaVhq9D8gYuZB4Xhp811zQmI3
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/Churn_Modelling - Churn_Modelling.csv")
df

# 1. Find the total number of customers in each country.
each_country = df['Geography'].value_counts()
each_country

# 2. Find the average credit score of customers based on gender.
avg_credit_score = df.groupby('Gender')['CreditScore'].mean()
avg_credit_score

# 3. Find the total number of customers who exited and customers who stayed.
cus_stayed = df['Exited'].value_counts()
cus_stayed

# 4. Find the average account balance in each country.
avg_bal = df.groupby('Geography')['Balance'].mean()
avg_bal

# 5. Find which age has the highest number of customers who exited the bank.
a = df.groupby('Age')['Exited'].value_counts()
# a
a.sort_values(ascending=False)
# a.max()

# 6. Find the average estimated salary of active and inactive members.
a = df.groupby('IsActiveMember')['EstimatedSalary'].value_counts()
a

# 7. Find the churn count based on the number of products customers are using.
churn_count = df.groupby('NumOfProducts')['Exited'].value_counts()
churn_count

# 8. Create a separate DataFrame containing country and region information, merge it with the
# main dataset using pd.merge(), and then find the average balance and average estimated
# salary by region.
cre_df = pd.DataFrame({
    'Geography': ['France', 'Germany', 'Spain'],
    'Region': ['Western Europe', 'Central Europe', 'Southern Europe']
})

result = pd.merge(Geography,Region, on='geography')
cre_df
avg_balance = df.groupby('Region')['Balance'].mean()
avg_estimated_salary = df.groupby('Region')['EstimatedSalary'].mean()

# df1.merge(df2, on='key_column', how='inner')

result = pd.merge(, avg_manufactuting_costs, on='geography')